name: 手动刷步数

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: 开始
        run: |
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}'
          skey='${{ secrets.SKEY }}'
          sckey='${{ secrets.SCKEY }}'
          position='${{ secrets.POSITION }}'
          corpid='${{ secrets.CORPID }}'
          corpsecret='${{ secrets.CORPSECRET }}'
          agentid='${{ secrets.AGENTID }}'
          touser='${{ secrets.TOUSER }}'
          toparty='${{ secrets.TOPARTY }}'
          totag='${{ secrets.TOTAG }}'
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          python3 manual.py ${user} ${passwd} ${skey} ${sckey} ${position} ${corpid} ${corpsecret} ${agentid} ${touser} ${toparty} ${totag} ${open_get_weather} ${area}
